# App configuration for cloud platforms like Google App Engine or similar services

runtime: nodejs18
env: standard
instance_class: F2

env_variables:
  NODE_ENV: "production"
  PORT: "8080"

handlers:
- url: /.*
  script: auto
  secure: always
