version: '3.8'

services:
  # النود جي اس (تطبيق الويب)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - yemen_market_network
    volumes:
      - app_uploads:/app/uploads
      - app_logs:/app/logs

  # قاعدة البيانات بوستجريسكل
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - yemen_market_network

  # سيرفر الويب وبروكسي عكسي
  web:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./client/dist:/usr/share/nginx/html
    depends_on:
      - app
    networks:
      - yemen_market_network

  # خدمة الذاكرة المؤقتة ريديس (اختياري)
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - yemen_market_network
    command: redis-server --appendonly yes

# الشبكات المشتركة
networks:
  yemen_market_network:
    driver: bridge

# المجلدات المستمرة
volumes:
  postgres_data:
  app_uploads:
  app_logs:
  redis_data: